# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "45500489ad79681d54783167405601a9"
name = "live-test-loyalty"
application_url = "https://shopify-loyalty-poc.onrender.com"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_app_proxy"

[auth]
redirect_urls = [ 
    "https://shopify-loyalty-poc.onrender.com/auth/callback",
    "https://shopify-loyalty-poc.onrender.com/auth/shopify/callback",
    "https://shopify-loyalty-poc.onrender.com/api/auth/callback"
 ]

[app_proxy]
url = "/my-app-proxy"
prefix = "apps"
subpath = "my-custom-path"